title: Stack Problems
description: My Personal Blog
author: Prawal Gangwar
github: https://github.com/prawalgangwar
about: I am a embedded software developer currently working at Texas Instruments.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/prawalgangwar"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/prawalgangwar"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/prawalgangwar"

share:
  twitter_username: prawalgangwar
  fb_appid:

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml
    - text: Travel
      url: /travel

url: "https://prawalgangwar.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
