title: Techilaa
description: My Personal Blog
author: Prawal Gangwar
github: https://github.com/prawalgangwar
about: I like systems 
disqus_shortname: techilaa
google_analytics: UA-101400553-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
  testimonials:
    output: true
    permalink: /:collection/:path

social:
    - icon: fa-facebook
      link: "https://facebook.com/prawalgangwar"
    - icon: fa-twitter
      link: "https://twitter.com/prawalgangwar"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/prawalgangwar"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/prawalgangwar"
    - icon: fa-instagram
      link: "https://instagram.com/prawalgangwar"
    - icon: fa-google-plus
      link: "https://plus.google.com/+PrawalGangwar"
share:
  twitter_username: prawalgangwar
  fb_appid:

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Resume
      url: https://prawalgangwar.github.io/vitae/
    - text: RSS Feed
      url: /feed.xml
    - text: Travel
      url: /travel

url: "https://prawalgangwar.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

disqus:
  shortname: techilaa
